openapi: 3.0.3
info:
  title: 小芽家教 - 学习记录 API
  description: |
    学习记录追踪 API，用于记录学生的学习活动、统计学习指标和生成学习进度报告。
  version: 1.0.0
  contact:
    name: 小芽家教开发团队

servers:
  - url: http://localhost:8000/api/v1
    description: 开发环境
  - url: https://api.sproutchat.com/api/v1
    description: 生产环境

tags:
  - name: Learning Records
    description: 学习记录管理
  - name: Learning Progress
    description: 学习进度和统计

paths:
  /learning/records:
    post:
      tags:
        - Learning Records
      summary: 创建学习记录
      description: |
        记录一次答题活动，包含问题内容、学生答案、正确答案等信息。
        如果学生答错，系统会自动创建错题记录并生成引导式反馈。
      operationId: createLearningRecord
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLearningRecordRequest'
            examples:
              correct_answer:
                summary: 答对示例
                value:
                  student_id: 1
                  question_content: "3 + 5 = ?"
                  question_type: "addition"
                  subject: "math"
                  difficulty_level: 1
                  student_answer: "8"
                  correct_answer: "8"
                  time_spent_seconds: 15
              wrong_answer:
                summary: 答错示例
                value:
                  student_id: 1
                  question_content: "3 + 5 = ?"
                  question_type: "addition"
                  subject: "math"
                  difficulty_level: 1
                  student_answer: "7"
                  correct_answer: "8"
                  time_spent_seconds: 20
      responses:
        '201':
          description: 学习记录创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LearningRecordResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '422':
          $ref: '#/components/responses/ValidationError'

    get:
      tags:
        - Learning Records
      summary: 查询学习记录列表
      description: |
        查询指定学生的学习记录，支持按时间范围、题目类型、是否正确等条件筛选。
        家长只能查询自己孩子的学习记录。
      operationId: listLearningRecords
      security:
        - BearerAuth: []
      parameters:
        - name: student_id
          in: query
          required: true
          schema:
            type: integer
          description: 学生 ID
          example: 1
        - name: start_date
          in: query
          schema:
            type: string
            format: date
          description: 开始日期（YYYY-MM-DD）
          example: "2025-01-01"
        - name: end_date
          in: query
          schema:
            type: string
            format: date
          description: 结束日期（YYYY-MM-DD）
          example: "2025-01-12"
        - name: question_type
          in: query
          schema:
            type: string
          description: 题目类型（如：addition, subtraction）
          example: "addition"
        - name: is_correct
          in: query
          schema:
            type: boolean
          description: 是否正确
          example: true
        - name: page
          in: query
          schema:
            type: integer
            default: 1
            minimum: 1
          description: 页码
        - name: page_size
          in: query
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
          description: 每页数量
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: 总记录数
                  page:
                    type: integer
                    description: 当前页码
                  page_size:
                    type: integer
                    description: 每页数量
                  records:
                    type: array
                    items:
                      $ref: '#/components/schemas/LearningRecordResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

  /learning/records/{record_id}:
    get:
      tags:
        - Learning Records
      summary: 获取学习记录详情
      description: |
        获取指定学习记录的详细信息，包括错题记录（如果存在）。
      operationId: getLearningRecord
      security:
        - BearerAuth: []
      parameters:
        - name: record_id
          in: path
          required: true
          schema:
            type: integer
          description: 学习记录 ID
          example: 123
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LearningRecordDetailResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

  /learning/progress:
    get:
      tags:
        - Learning Progress
      summary: 获取学习进度统计
      description: |
        获取学生的学习进度统计数据，包括总题数、正确率、连续答对次数等指标。
      operationId: getLearningProgress
      security:
        - BearerAuth: []
      parameters:
        - name: student_id
          in: query
          required: true
          schema:
            type: integer
          description: 学生 ID
          example: 1
        - name: time_range
          in: query
          schema:
            type: string
            enum: [today, week, month, all]
            default: all
          description: 时间范围
          example: "week"
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LearningProgressResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

  /learning/report:
    get:
      tags:
        - Learning Progress
      summary: 生成学习进度报告
      description: |
        生成学生的学习进度报告，包含学习统计、按题型正确率分布、按难度等级表现等。
      operationId: generateLearningReport
      security:
        - BearerAuth: []
      parameters:
        - name: student_id
          in: query
          required: true
          schema:
            type: integer
          description: 学生 ID
          example: 1
        - name: start_date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: 报告开始日期
          example: "2025-01-01"
        - name: end_date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: 报告结束日期
          example: "2025-01-12"
      responses:
        '200':
          description: 报告生成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LearningReportResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT 认证，格式：`Bearer <token>`

  schemas:
    CreateLearningRecordRequest:
      type: object
      required:
        - student_id
        - question_content
        - question_type
        - subject
        - student_answer
        - correct_answer
        - time_spent_seconds
      properties:
        student_id:
          type: integer
          description: 学生 ID
          example: 1
        question_content:
          type: string
          maxLength: 1000
          description: 问题内容
          example: "3 + 5 = ?"
        question_type:
          type: string
          description: 题目类型
          enum: [addition, subtraction, multiplication, division, word_problem]
          example: "addition"
        subject:
          type: string
          description: 科目
          enum: [math, chinese, english]
          example: "math"
        difficulty_level:
          type: integer
          minimum: 1
          maximum: 5
          description: 难度等级（1-5）
          example: 1
        student_answer:
          type: string
          maxLength: 500
          description: 学生答案
          example: "8"
        correct_answer:
          type: string
          maxLength: 500
          description: 正确答案
          example: "8"
        time_spent_seconds:
          type: integer
          minimum: 0
          description: 答题耗时（秒）
          example: 15

    LearningRecordResponse:
      type: object
      properties:
        id:
          type: integer
          description: 学习记录 ID
          example: 123
        student_id:
          type: integer
          description: 学生 ID
          example: 1
        question_content:
          type: string
          description: 问题内容
          example: "3 + 5 = ?"
        question_type:
          type: string
          description: 题目类型
          example: "addition"
        subject:
          type: string
          description: 科目
          example: "math"
        difficulty_level:
          type: integer
          description: 难度等级
          example: 1
        student_answer:
          type: string
          description: 学生答案（已解密）
          example: "8"
        correct_answer:
          type: string
          description: 正确答案
          example: "8"
        is_correct:
          type: boolean
          description: 是否正确
          example: true
        time_spent_seconds:
          type: integer
          description: 答题耗时（秒）
          example: 15
        created_at:
          type: string
          format: date-time
          description: 创建时间
          example: "2025-01-12T10:30:00Z"

    LearningRecordDetailResponse:
      allOf:
        - $ref: '#/components/schemas/LearningRecordResponse'
        - type: object
          properties:
            wrong_answer_record:
              type: object
              nullable: true
              description: 错题记录（如果学生答错）
              properties:
                id:
                  type: integer
                  example: 456
                error_type:
                  type: string
                  enum: [calculation, concept, understanding, careless]
                  example: "calculation"
                guidance_type:
                  type: string
                  enum: [clarify, hint, break_down, visualize, check_work, alternative_method, encourage]
                  example: "hint"
                guidance_content:
                  type: string
                  example: "让我来帮你检查一下。你一开始有 3 个苹果，妈妈又给了你 3 个，你能用手指或画图的方式数一数，3 加 3 等于多少吗？"
                is_resolved:
                  type: boolean
                  example: false

    LearningProgressResponse:
      type: object
      properties:
        student_id:
          type: integer
          example: 1
        total_questions:
          type: integer
          description: 总题数
          example: 50
        correct_count:
          type: integer
          description: 正确题数
          example: 40
        wrong_count:
          type: integer
          description: 错误题数
          example: 10
        accuracy_rate:
          type: number
          format: float
          description: 正确率（百分比）
          example: 80.0
        current_streak:
          type: integer
          description: 当前连续答对次数
          example: 5
        longest_streak:
          type: integer
          description: 最长连续答对记录
          example: 12
        total_time_spent_seconds:
          type: integer
          description: 总学习时长（秒）
          example: 1800
        average_time_per_question_seconds:
          type: number
          format: float
          description: 平均每题用时（秒）
          example: 36.0
        time_range:
          type: string
          description: 统计时间范围
          example: "week"

    LearningReportResponse:
      type: object
      properties:
        student_id:
          type: integer
          example: 1
        period:
          type: object
          properties:
            start_date:
              type: string
              format: date
              example: "2025-01-01"
            end_date:
              type: string
              format: date
              example: "2025-01-12"
        summary:
          type: object
          description: 学习摘要
          properties:
            total_questions:
              type: integer
              example: 50
            correct_count:
              type: integer
              example: 40
            wrong_count:
              type: integer
              example: 10
            accuracy_rate:
              type: number
              format: float
              example: 80.0
            total_time_seconds:
              type: integer
              example: 1800
        by_question_type:
          type: array
          description: 按题型统计
          items:
            type: object
            properties:
              question_type:
                type: string
                example: "addition"
              total_count:
                type: integer
                example: 20
              correct_count:
                type: integer
                example: 18
              accuracy_rate:
                type: number
                format: float
                example: 90.0
        by_difficulty_level:
          type: array
          description: 按难度等级统计
          items:
            type: object
            properties:
              difficulty_level:
                type: integer
                example: 1
              total_count:
                type: integer
                example: 30
              correct_count:
                type: integer
                example: 28
              accuracy_rate:
                type: number
                format: float
                example: 93.33
        streak_records:
          type: object
          description: 连续答对记录
          properties:
            current_streak:
              type: integer
              example: 5
            longest_streak:
              type: integer
              example: 12
        time_distribution:
          type: object
          description: 时间分布
          properties:
            average_time_per_question:
              type: number
              format: float
              example: 36.0
            fastest_time_seconds:
              type: integer
              example: 10
            slowest_time_seconds:
              type: integer
              example: 120

  responses:
    BadRequest:
      description: 请求参数错误
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Invalid request parameters"

    Unauthorized:
      description: 未认证
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Not authenticated"

    Forbidden:
      description: 无权限访问
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "You do not have permission to access this resource"

    NotFound:
      description: 资源不存在
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Learning record not found"

    ValidationError:
      description: 请求体验证错误
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: array
                items:
                  type: object
                  properties:
                    loc:
                      type: array
                      items:
                        type: string
                      example: ["body", "student_answer"]
                    msg:
                      type: string
                      example: "field required"
                    type:
                      type: string
                      example: "value_error.missing"
